# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# Define the used images
node8: &node8
  working_directory: &workdir_node8 ~/shared-utils/node8
  docker:
    - image: circleci/node:8

node10: &node10
  working_directory: &workdir_node10 ~/shared-utils/node10
  docker:
    - image: circleci/node:10

node12: &node12
  working_directory: &workdir_node12 ~/shared-utils/node12
  docker:
    - image: circleci/node:12

# use "latest" for lint and publish
latest: &latest
  working_directory: &workdir_latest ~/shared-utils/latest
  docker:
    - image: circleci/node

# some job filters
tags_and_branches: &tags_and_branches
  filters:
    tags:
      only: /^v.*/

only_tags: &only_tags
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

# Which files to preserve between jobs
whitelist: &whitelist
  paths:
    - build/*
    - node_modules/*
    - src/*
    - test/*
    - coverage/*
    - .npmignore
    - package.json
    - README.md
    - tsconfig.json
    - tslint.json

version: 2
jobs:
# ----------------------------------------------------
  test_node8:
    <<: *node8

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-node8-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Remove unnecessary Dependencies
          command: npm ls || true ; npm prune

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node8-{{ checksum "package.json" }}

      - run:
          name: Run component tests
          command: npm run test

# ----------------------------------------------------
  test_node10:
    <<: *node10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-node10-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Remove unnecessary Dependencies
          command: npm ls || true ; npm prune

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node10-{{ checksum "package.json" }}

      - run:
          name: Run component tests
          command: npm run test

# ----------------------------------------------------
  test_node12:
    <<: *node12

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-node12-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Remove unnecessary Dependencies
          command: npm ls || true ; npm prune

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node12-{{ checksum "package.json" }}

      - run:
          name: Run component tests
          command: npm run test

# ----------------------------------------------------
  test_latest:
    <<: *latest

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-latest-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Remove unnecessary Dependencies
          command: npm ls || true ; npm prune

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-latest-{{ checksum "package.json" }}

      # on latest also lint the code
      - run:
          name: Lint TypeScript code
          command: npm run lint

      - run:
          name: Run component tests
          command: npm run test

      # persist the build files, so we can pick them up in the deploy job
      - persist_to_workspace:
          root: *workdir_latest
          <<: *whitelist

# ----------------------------------------------------
# generates a clean build of the TypeScript sources
# to make sure there were no leftover build files
  coverage:
    <<: *latest

    steps:
      - attach_workspace:
          at: *workdir_latest

      - run:
          name: Generate coverage report
          command: npm run coverage

      - run:
          name: Upload it to coveralls.io
          command: COVERALLS_SERVICE_NAME="CircleCI" COVERALLS_SERVICE_JOB_ID="$CIRCLE_BUILD_NUM" npm run coveralls

# ----------------------------------------------------
# generates a clean build of the TypeScript sources
# to make sure there were no leftover build files
  build:
    <<: *latest

    steps:
      - attach_workspace:
          at: *workdir_latest

      - run:
          name: Clean previous builds
          command: npm run prebuild

      - run:
          name: Build the source files
          command: npm run build

      - persist_to_workspace:
          root: *workdir_latest
          <<: *whitelist

# ----------------------------------------------------
# Deploys the final package to NPM
  deploy:
    <<: *latest

    steps:
      - attach_workspace:
          at: *workdir_latest

      - run:
          name: Flatten the build directory structure
          command: cd build && cp *.{ts,js} .. && cp --parents ./**/*.{ts,js} .. && cd .. && rm -rf build
      - run:
          name: Replace all references inside package.json
          command: sed -i 's/build\/index\./index\./' package.json

      - run:
          name: Login to npm
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: Publish package to npm
          command: npm publish

# ----------------------------------------------------
# Fit it all together
workflows:
  version: 2

  test-and-deploy:
    jobs:
      - test_node8:
          <<: *tags_and_branches
      - test_node10:
          <<: *tags_and_branches
      - test_node12:
          <<: *tags_and_branches
      - test_latest:
          <<: *tags_and_branches

      - coverage:
          requires: 
            - test_latest
          <<: *tags_and_branches

      # build only on tagged builds and if all tests succeeded
      - build:
          requires: 
            - test_node8
            - test_node10
            - test_node12
            - test_latest
          <<: *only_tags

      # deploy only on tagged builds and if all tests succeeded
      - deploy:
          requires:
            - build
          <<: *only_tags
